apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Yf9nj25wbpttjHiQ4vLKpNIIZ2c+H8DyqjfC91rwxU4//lmi8HmdqDo=,iv:twis9oVAxBrkybB1QL0kywIyBOYtMCjhQiYArnNYoI0=,tag:8V4BuENRNy/uJvPLzCAfjg==,type:comment]
    PODINFO_DOMAIN_NAME: ENC[AES256_GCM,data:isZE0X7BXjNiI9z6iY1NopdMIJBU,iv:uvT4EjrzS5w97zGF2d4gBF3M2a6CQY+YUv/oCphe6Mc=,tag:XLaBO6AFjK1ttjzHHJrggQ==,type:str]
    #ENC[AES256_GCM,data:ZcWq/HhVG44R1aJKyEUIpPvQxRtwn6ZGObFLehuH71IxMIKK6GfgOg==,iv:C/7iG+hUl+gBs0Lz4f6aX7TPNPss2D8ROMDvhENXsEs=,tag:RdUMSx7nDv0hPW0GV5fH1A==,type:comment]
    MEALIE_DOMAIN_NAME: ENC[AES256_GCM,data:GGZluO0EScPDawlxZMKrexznAbI=,iv:Z7o1Oc0AQPUlZSSJ6CAbPGLN8SG2GDxEq9LrLgKZzSg=,tag:h5z3fqqQEpHWivUok1iAZg==,type:str]
    EXTERNAL_DNS_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:yRhJQ0n48sCe6W/O2Uw20y7maaXTYuaKlxvoSw0C5Wy7gCesnyledA==,iv:dM3YkBEl46kztKcqW1XhjGjNRD/iv9UDT3nYXHhSoew=,tag:xXZdVtTZ4Kwr5wHQ30YnUA==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9SteYzwzR3YNPP8KoJO5MfTtOoMcH5/SiH70Pw==,iv:8dp6bSplKBOhCfhuZUV19M4n1JzZj+g0A+uqbJBHvO0=,tag:LQOLy/mej0agmZ0x5ebXXA==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:4rJFawZwix4vOCjzFmD23T4VnoO0xE3vOxMpyg==,iv:1qsI/0OD4phViglQ21V1LAXxEl3I/q6gNmifkQQPwMM=,tag:IF/0YZq1VcCs8dVh8azpUQ==,type:str]
    FLUX_NOTIFICATION_DOMAIN_NAME: ENC[AES256_GCM,data:OSL7z7/5PhafFeDbZBp/2zvP30M/Wyd3Yi+GHvMwGA==,iv:2bsGGs4V3gMa3JrQGX3xwLHJrhp1BC6KooTdhsHpHEs=,tag:RmP3eX5jUAsmR/43wu9d2g==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:mjVWHzL9EAGDSAHb5w==,iv:1hHPaQKm+1dGy8d+7EYAMjkMMYgWJCrxkZ4s+WI0Qok=,tag:ylMrmnogx4+orJ/dnA2ZIA==,type:str]
    NFS_PATH: ENC[AES256_GCM,data:0ceU2f1KRNuupw3RbwdMQQ==,iv:6MSIkrlITtvJm1XE8z+8eDjRmRef3Er5CS8M5wxibLI=,tag:uQhrCmWyD3sTaDkMt3MSoQ==,type:str]
sops:
    lastmodified: "2026-06-21T18:19:59Z"
    mac: ENC[AES256_GCM,data:UFZNupfJ3obiBzazH3oCcFDcP+8VkOkaV+2YecGm4qFkyebXoHryoVqV5mVW3lL1yCJ30TgTkTnLZnSnTe2tggkQI8hAmXiwA5NWAEJef/R9lqoltQheX+B4DMXiOYCOfmR3i/j/jx7UT4c9Llbl/pIyADuuKKTwunfQLrmOIk4=,iv:JLSAmK7ei273nonvqdeoAlkANXJCDsQ97TqlOSkzXL4=,tag:0LWjyHvOgUB6N62eWqp48Q==,type:str]
    pgp:
        - created_at: "2026-06-21T18:19:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1X/kZ4Jzp5jAQ//Q1XVeJsd0NJM3tMwTWgC9L9Ox9WZYS8HEUc+wLjOrnuu
            Q5+8is3HNQHd2fqvutSVm3lyFmkY+zlaQumzSctqQ5VrbwnoneLSCz5M/Sc2LsyV
            D3ph6dxHZvWrqTXH3h7CuuNMVgUbFQD0Q1O7qpSqwtx5BSnD16wDhOZezsb1vKHL
            ab8vKssx1tPhp2n6h5zTX5vKpKLNOjvFK4wfDdXIRojh0vmHuTJcyM3xPz+a8MkD
            sbkC+4GVBUtZlQlqb3NjGPPzlSVZTCQCSO7W1YhPwdaYqg/Ztqpk8gxTPG81yhMn
            S2MwRXTtrxuNISIZMKQagcilkdeddnuxUC1m5XVFBoB1YyrgNQfHqoLtiJIBZVGS
            s0KfR7nOUWELn1OmioT/BtaU/Xd/lbhSWNYWzEHNRxCw2g8rxwexrJdCVIkQOeXY
            o0S/QyvHqhQFYqYTkPbEtnLNy7JAQDsLSVOjxXdVZjuUNWbIvfTitX+IJ6Zg5i4h
            Sabkg0m+4k+57k0VlX40ePNHtmTwsOkxbL/KfAaRBOgy20MubrVyzQbw4QWhfTuc
            csft+TZYJwiVYu0tEq63mL4btho71M/XAIaENZEBYuULppFwNBqNyg6cULJ93RE4
            1xAahUXCrZkKqjtxgDliJMkCH6YngSdIrxxrqDJsuo5xl9CDfYjVHtuVo+lBSK7S
            XAEjsM9+gDWkC2KJF+fpOMdnTV30PM2vKlL9uF9MZiEOMVmVaaeJBEbcIQ4W2DRo
            T4qVn/9KRiq4iAVu0TPZNF8pMjzjpjEKFV9Z1FG3WI7EgT+pLc/PtceKxXbL
            =Vc5B
            -----END PGP MESSAGE-----
          fp: 7A5DC69AD7F7A05AAF22EBD8005B9C45909B266E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
