apiVersion: v1
kind: Secret
metadata:
  name: kia-poller
  namespace: default
type: Opaque
stringData:
  BLUELINK_REFRESH_TOKEN: REPLACE_ME
  INFLUX_URL: http://influxdb.monitoring.svc.cluster.local:8086
  INFLUX_TOKEN: REPLACE_ME
  INFLUX_ORG: home
  INFLUX_BUCKET: kia
  PG_DSN: postgresql://kia:REPLACE_ME@postgres.default.svc.cluster.local:5432/kia
