apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre
spec:
  interval: 1h
  timeout: 5m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/calibre
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
