apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secrets.yaml
  - ./mongodb.yaml
  - ./kafka.yaml
  - ./keycloak.yaml
  - ./core-api.yaml
  - ./base-station.yaml
  - ./ingress.yaml
