apiVersion: apps/v1
kind: Deployment
metadata:
  name: sump-it
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sump-it
  template:
    metadata:
      labels:
        app: sump-it
    spec:
      containers:
        - name: sump-it
          image: ghcr.io/orriborri/sump-it:sha-ef8b70b
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
          - secretRef:
              name: sump-it-postgres-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PORT
              value: "8080"
