apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./service.yaml
- ./ingress.yaml
- ./sump-it-config.yaml
images:
- name: ghcr.io/orriborri/sump-it
  newName: ghcr.io/orriborri/sump-it
  newTag: sha-c43af98
