apiVersion: v1
kind: Secret
metadata:
    name: sump-it-postgres-config
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:pt/FvcuhfOOnQVWnLZeCYEP26bOQUuFdH/UHGKpyiJC8EIcam1p8Cm3Oy7xsl+O6YL0VSEApVZP3Duks,iv:NrdcBVx+BsjXLkbsWVcYdMYzwA3mSovwvuBMOPkk7WM=,tag:7qGSmX901RAWYTjxGcaVHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-10T18:29:31Z"
    mac: ENC[AES256_GCM,data:/Dz9K+zWwLfaKW1LGNQIYFAj8HqN4+QyFobHp/0RvrNlm+Nm/7XcB23VbtxYG1ysmh5kEiMU94tlbtWZ31kDFHtTI5mPVTVtYmDcWwkcJy5LYBFYap1GxC3lMSya1XyViyawyYva5JgNczlvOywalwIsK+Jb6WhG+QkJxQDpx5Y=,iv:RH7BYeqqP+612nYlDFHjnUePVBQyeR+T8Pvk6loqZ6g=,tag:ZAIf8Z10KL6NVyS8mrZBpQ==,type:str]
    pgp:
        - created_at: "2025-09-10T18:29:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1X/kZ4Jzp5jAQ//UPaATZDoavIkeCzVI1tPqonBSLNnvaYHH2uPWBdEhpAj
            QJTADa5v/ao/1wNwMg0GjDHmWMaLr8tvAFfZVMizAlO7Jve6JF4bsSvjZ3GQaLmW
            0kJhE9wdqmfqTIqG3/yLnMJRINs4eFPskxqJuPe4dWeA8h40DxL4DisdufRHFODV
            aL8gVPjHO+84obg7o2GkYzky1Sb8LDmuM22yOxAHlTkwsZ00IOPU/TUIQHPKJS7z
            0BptcMcnX8INrLMLXxpXsG2d8C++IVrcFZTj/pH7b72a7kVjToM4zMle4i/JCRzk
            UPokOc654ZQDofIm33otwpZhJg4ki/OjE7Y/ZTCNh5j1CZ2mRy7vVCuUhSnWKozY
            vQaGuJTIB29xwkvINZnS9O3B+3sj7fm3ltTiDIrUbs5brvji4n6P4E2nC32NwWLl
            99MybMKBQLdWL41yMQz0fyrI7J1ZnYIYZph0NwoHAflg9qLjkuRctu9p+vY2AGys
            uCQ45v10q9u8KY8KEmyY+ffcZh7UlwtrDvCTyEjji9u9hboP2f78EAWQ1WsjsnTB
            px8LmzM1Ghn7x3/FYIjWtKoXQFNGwmcOVp+yqQdi0zQBW/+9rLppqIIdRRyA2YsR
            RME39ceDISMwak2l5TU62xjMLSn4AEXZciEZf/czMqOt7MjpTdbe2/QPQRcdk7fU
            aAEJAhCrTwsqne0S6Bpb2tV4+kPxfwz7GDQ8g/i4a+/QJL99W62X4vP1wQD0i3PM
            A+TTVT4yLkiaqiTBizVVM4IpI6glcLb6v6CKSfDeQ2XKE1kQRj5A1peDIRjPyUS+
            HPXdOqTxv8Ty
            =mfqJ
            -----END PGP MESSAGE-----
          fp: 7A5DC69AD7F7A05AAF22EBD8005B9C45909B266E
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
