apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  ingressClassName: private
  tls:
    - secretName: orriborri-com-tls
  rules:
    - host: ${HOME_ASSISTANT_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: home-assistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      port: 8123
  persistance:
    enabled: true
    accessMode: ReadWriteMany
