apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Portfolio</title>
        <style>
            body { margin: 0; padding: 0; overflow: hidden; }
            iframe { position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0; }
        </style>
    </head>
    <body>
        <iframe src="https://1drv.ms/p/c/f90c7327857394f1/IQS_IETy_Q-nSocOg53HNpPcAdnhMXQD-fSjHa3CjYQvHhQ?em=2&amp;wdAr=1.7777777777777777&amp;wdEaaCheck=0">
            This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.
        </iframe>
    </body>
    </html>
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-server
  namespace: default
spec:
  selector:
    app: portfolio-server
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-server
  template:
    metadata:
      labels:
        app: portfolio-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: html
        configMap:
          name: portfolio-html
          items:
          - key: index.html
            path: index.html
      - name: config
        configMap:
          name: portfolio-html
          items:
          - key: default.conf
            path: default.conf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuuli-portfolio-redirect
  namespace: default
spec:
  ingressClassName: public
  rules:
  - host: tuuli.vetelainen.fi
    http:
      paths:
      - path: /portfolio
        pathType: Prefix
        backend:
          service:
            name: portfolio-server
            port:
              number: 80
  - host: tuuli.orriborri.com
    http:
      paths:
      - path: /portfolio
        pathType: Prefix
        backend:
          service:
            name: portfolio-server
            port:
              number: 80
