apiVersion: v1
kind: Pod
metadata:
  name: debug-nfs
spec:
  containers:
  - name: debug
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt/nfs
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: postgres17-data
