apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fireflyiii
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: firefly.orriborri.com
spec:
  type: LoadBalancer
  selector:
    app: fireflyiii
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fireflyiii
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fireflyiii
  template:
    metadata:
      labels:
        app: fireflyiii
    spec:
      containers:
        - name: fireflyiii
          image: fireflyiii/core:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: firefly-config
          volumeMounts:
            - mountPath: /var/www/html/storage/upload
              name: firefly-data
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      
      volumes:
        - name: firefly-data
          persistentVolumeClaim:
            claimName: firefly-data
