apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly
  namespace: default
spec:
  interval: 1h
  timeout: 1m
  chart:
    spec:
      chart: firefly-iii
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: firefly
        namespace: flux-system
  values:
    persistence:
      enabled: true
      accessMode: ReadWriteMany
    service:
      type: LoadBalancer
      port: 80
    config:
      env:
        DB_CONNECTION: "pgsql" # Ensure all values are strings
        DB_USER: "firefly"
        DB_DATABASE: "firefly"
        DEFAULT_LANGUAGE: "en_FI"
        DEFAULT_LOCALE: "equal"
        TZ: "Europe/Helsinki"
        DB_PORT: "5432" # Quote numeric values
        envValueFrom:
          APP_SECRET:
            secretKeyRef:
              name: firefly
              key: APP_SECRET
          DB_PASSWORD:
            secretKeyRef:
              name: firefly
              key: DB_PASSWORD
