apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinepods-downloads
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinepods-backups
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
