apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0 # Changed from 3.12.0 to match pulled version
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
    resources:
      requests:
        memory: 32Mi
        cpu: 25m
      limits:
        memory: 64Mi
        cpu: 50m
