apiVersion: batch/v1
kind: Job
metadata:
  name: wger-db-init
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: postgres:16-alpine
          command:
            - /bin/sh
            - -c
            - |
              # Wait for postgres to be ready
              until pg_isready -h postgres -p 5432; do
                echo "Waiting for postgres..."
                sleep 2
              done
              
              # Create database if it doesn't exist
              psql -h postgres -U $PGUSER -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'wger'" | grep -q 1 || psql -h postgres -U $PGUSER -d postgres -c "CREATE DATABASE wger;"
              
              echo "Database initialization complete"
          envFrom:
            - secretRef:
                name: postgres-config
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: PGPASSWORD
