apiVersion: apps/v1
kind: Deployment
metadata:
  name: wger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger
  template:
    metadata:
      labels:
        app: wger
    spec:
      initContainers:
        - name: wger-migrate
          image: wger/server:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wger-secrets
                  key: DJANGO_SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/wger"
            - name: CACHE_URL
              value: "redis://redis-wger:6379/1"
            - name: DJANGO_DEBUG
              value: "False"
            - name: WGER_INSTANCE
              value: https://wger.orriborri.com
            - name: ALLOW_REGISTRATION
              value: "True"
            - name: ALLOW_GUEST_USERS
              value: "True"
          volumeMounts:
            - name: media-storage
              mountPath: /home/wger/media
            - name: static-storage
              mountPath: /home/wger/static
      containers:
        - name: wger
          image: wger/server:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wger-secrets
                  key: DJANGO_SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/wger"
            - name: CACHE_URL
              value: "redis://redis-wger:6379/1"
            - name: DJANGO_DEBUG
              value: "False"
            - name: WGER_INSTANCE
              value: "https://${WGER_DOMAIN_NAME}"
            - name: ALLOW_REGISTRATION
              value: "True"
            - name: ALLOW_GUEST_USERS
              value: "True"
            - name: EXERCISE_CACHE_TTL
              value: "18000"
            - name: SITE_URL
              value: "https://${WGER_DOMAIN_NAME}"
          volumeMounts:
            - name: media-storage
              mountPath: /home/wger/media
            - name: static-storage
              mountPath: /home/wger/static
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: wger-media-pvc
        - name: static-storage
          persistentVolumeClaim:
            claimName: wger-static-pvc
