apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.yaml
  - ./pvcs.yaml
  - ./db-init.yaml
  - ./redis.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
