apiVersion: batch/v1
kind: Job
metadata:
  name: wger-postgres-init
  namespace: wger
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: postgres-init
          image: postgres:17
          env:
            - name: PGHOST
              value: postgres.default.svc.cluster.local
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: wger-secrets
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: wger-secrets
                  key: POSTGRES_PASSWORD
          command:
            - /bin/bash
            - -c
            - |
              echo "Creating wger database if it doesn't exist..."
              psql -tc "SELECT 1 FROM pg_database WHERE datname = 'wger'" | grep -q 1 || psql -c "CREATE DATABASE wger;"
              echo "Database initialization complete"
