---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-media-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: syno-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-static-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: syno-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-wger-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: syno-storage
