apiVersion: v1
kind: Secret
metadata:
  name: wger-secrets
  namespace: wger
type: Opaque
stringData:
  DJANGO_SECRET_KEY: ${WGER_DJANGO_SECRET_KEY}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.default.svc.cluster.local:5432/wger
