apiVersion: v1
kind: Service
metadata:
  name: wger
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wger
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
