apiVersion: v1
kind: Secret
metadata:
  name: kitchenowl-secret
  namespace: default
type: Opaque
stringData:
  JWT_SECRET_KEY: MSoZYJlRiiLkirYSmRlUUn2yXwF2amQwUqSH8AuC98M
  FRONT_URL: https://food.orriborri.com
