apiVersion: v1
kind: Secret
metadata:
    name: kitchenowl-secret
    namespace: default
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:xqW6RQjOe8kwHenBAhzpFFkuGiCvj/1qTjBHhl+9kmgj4e/X4BpTcKtcpQ==,iv:E+1gK3b55iuk0i6qY5RZtuPTI1jNMV67LAlBKTMIu1U=,tag:O073zAR8oPOLJ4OY82+q7w==,type:str]
    FRONT_URL: ENC[AES256_GCM,data:R/rMOfc/0vpGvuBql67MlTUIvA6y/r4tbKs=,iv:xyE7F4QMbvzTXOX4Zii/MkRXmm8iMLqcr9NQKz8u/RI=,tag:np/hFA/mHUPclAp9t+EAVw==,type:str]
sops:
    lastmodified: "2026-06-21T17:45:37Z"
    mac: ENC[AES256_GCM,data:NQPijWHdKTnz3DR1k5ibYkMDFBnNUeuFcJTynZACe2KIXe/o7U5Jb2f7BCAlbbR4bqpyGMmJzunrLjPgBEECIcXQCGXKeNJV/2hOajZlNxw89nSvspNttnJJdE8wrAPmQuNy4hX7wiJRp/m4UshaRKi295um2cBaujxWAeTaV+Q=,iv:lGILfIa9yJlFiLmHbzeTG9BinOV2pEFMALzzxk8DL94=,tag:OLou8cqie9C0FHY8FDcN8Q==,type:str]
    pgp:
        - created_at: "2026-06-21T17:45:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1X/kZ4Jzp5jAQ//cCuYHj1+hehXZM+9eBQaUsJLb21V654X7NO+g3ECaH7/
            KKzmt80+fHkmAAjf0mEPEl4Zlvs7IiLo+27Pa0rA2HmINJ8I7Jcv2208r9aCojQ3
            86ZntU+PB6qJjopdy7xiarhaGsPRQmRzy7C6DSBGJlZXX/oto7L1WdbGo9WRzdeg
            ahKItUsJtz8G/DqliPQOrsnINskYIzFgETjDtIrkQ2ZlZc4z6RwNhCcDTtzYIr/i
            +qka4lz6gn7nkeO0s2Q/eozDlP1TkVMHFSvaIOoVRWewxGcD/GeyX66f/w+IetgG
            8uInsNn0ezgyA76CtS3HGtMDtdDM56p3oPnsmlXAxW2oTvaIULWFRBMHmaefo5eq
            +zEzyl8tWuJOO4Z9W+OibYQ0nUaOgL4zeSReK6MUB6X/h8R2DMGWIS5ZTRVZCbWu
            QtPWUYIG1iJbK/7HeZlYiRyQobhGlNPlXzkLAe72Rq7/lest/4fuxH9EBQuxOSDr
            +k69AXKx5KRvsA4I1Wa709kD4Vs/3Vzp34c9tMQrPtNsgOXriOD1RqnoWkGiSkAC
            arCSWaunjHcUniqQjR9j0KARs01rp6G/1WNZyM1HskC1EDy4CB+w+Mdr8ZxDDJ/A
            7skR2eVlxQAQ9+8b479EmmuMOjaZuRZORPMdBjR3UVo6qMeVBXTr5LZGZfqdCrDS
            XAHs9KjLhDx2sk1hrJzBl0eKjAriILBYAHFqkfHUzEEKX7qU7MzBXZl2pashmlJf
            4ZC5Fd2N3G1cbmAex7GhJ5d/kEC/dGWoejfcvdayEAmf94jAI7HvjQRBqAaV
            =cfwH
            -----END PGP MESSAGE-----
          fp: 7A5DC69AD7F7A05AAF22EBD8005B9C45909B266E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
