apiVersion: v1
kind: Namespace
metadata:
  name: nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}
    storageClass:
      name: nfs-client
      defaultClass: false
      accessModes: ReadWriteMany
      reclaimPolicy: Delete
      archiveOnDelete: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
