apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  interval: 1h
  timeout: 3m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.x
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    storageClass:
      name: homelab-nfs
      reclaimPolicy: Retain
    nfs:
      server: 192.168.1.244
      path: /volume3
      mountOptions:
        - nfsvers=3
        - timeo=600
        - retrans=3
