apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.17.0@sha256:85eba2727b410c8f8093d641a4b1a29671878db94d525a70a4108d10ba8eef5f
          args:
            - --source=service
            - --source=ingress
            # TODO: replace annotation filter with ingress class filter, which will be supported in a future version of external-dns
            # - --ingress-class=private
            - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
            - --domain-filter=orriborri.com
            - --provider=cloudflare
            - --cloudflare-dns-records-per-page=5000
          env:
            - name: CF_API_EMAIL
              value: ${CLOUDFLARE_EMAIL}
            - name: CF_API_TOKEN
              value: ${EXTERNAL_DNS_CLOUDFLARE_API_TOKEN}
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
