apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-data
  namespace: default
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: znc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: public
  tls:
    - secretName: orriborri-com-tls
  rules:
    - host: znc.orriborri.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: znc
                port:
                  number: 443
---
apiVersion: v1
kind: Service
metadata:
  name: znc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: znc
  ports:
    - name: web
      protocol: TCP
      port: 443
      targetPort: 6501
    - name: irc
      protocol: TCP
      port: 6697
      targetPort: 6697
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: znc
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: znc
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: znc
          image: docker.io/linuxserver/znc:1.9.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6501
            - containerPort: 6697
          env:
            - name: TZ
              value: "Europe/Helsinki"
          volumeMounts:
            - mountPath: /config
              name: znc-data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: znc-data
          persistentVolumeClaim:
            claimName: znc-data
