apiVersion: v1
kind: Secret
metadata:
    name: postgres-config
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:a4b8fauR,iv:uOCRvXH2ZrdZFRWZ+r23QZIDt9c4tgqhkK4ejEb+vXs=,tag:hv/1gCoHqMr3Mn2gS+0+ug==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:C+zxB+lIacC0ZkVdIyj6h/z4ROw=,iv:whCEKwGvPX9RMuEBTAo96297Iag6ZgKi160jaqb1aWQ=,tag:jlrjB5Sg+zc7FQnNpJD/CQ==,type:str]
    PGHOST: ENC[AES256_GCM,data:/P0FvSwjFw7hDNexUkRrF9wgqHBAtg==,iv:np+uFTQ7x2BqFMVGZjbvcUYmG8wzuRijl2/DWU864Ew=,tag:/bWrKQ0lNx0fwq1genEsFw==,type:str]
    PGUSER: ENC[AES256_GCM,data:dBSTFT/o,iv:TBCPwnmEYmU7rGbO0+JU8201egkWGnF03ApAM3hhB4g=,tag:rObF1/JnbugPdOLUrCpv8A==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:pn+0jyOtLicn2yuv0aOk6lZcqFg=,iv:f8bQz6y38EB5uIbhBTsUWWq3lljdSMh3l/y4C9sWBV4=,tag:pNToBpL0lUofqiUXdP2yzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-14T15:08:51Z"
    mac: ENC[AES256_GCM,data:zmcWtNX5gKDhmg7nxzkUOs4EAS+NeBItWx4fXPWni4MjPKTSXL2oJ4pGNOt1GqtEgg4EnqfUH75YZIAN2dv9xy0NmF8wbHw2Td6T9hAuLt9xoJtoH1lr58fxe1bwK2ALNsYkUzmLB684t4VgAQXusJ6F4gZXxV5qMQ5iY1enTrA=,iv:lfSg+BZOA6pqqO+PwwbNTbAtfKTbxjtVXNIjIT85M7c=,tag:+D8Q0OoCAHefhfbVgUfShA==,type:str]
    pgp:
        - created_at: "2024-09-06T04:54:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1X/kZ4Jzp5jAQ//Z/ODH0T2vBBoqVe5JeTFD6y6ICTey8UEZxYbynQ6b0TR
            CyLkVrhFuD2DzvrMIpWDtcKiFW2MX7eV5ddorEL0+csI32aLkClBTyfOTVak6LUD
            JHGY7QA3xHqzKn6rWyWWnGOjwIB0iFATNysYNonSncjnKxGy4u4uhlkA5Aud7Wgc
            VyuT6wj7EkSTDQ8p8tMSVRG6sT+ld20jYbNfdsHXRVL6jpev4SePnzW3aQMo92OM
            4BupoLpPv4kLVTPFEW04bfH791eXQ/+wpiBYyyycG3kW+6pPZhs9Oy6Dnz4+MdE3
            jS6koKuhsRko7GRsfF91iwag+y5zhVT4Qp4JTGSgpYhPFf0CZRyo7GfA+pjodF0U
            1YYmzRnM7BBINKN7RDX6EKU+mylVcQ7SAlDLZIy/PuaIVGJ+6PqdExldKA8Cuve/
            EPYTzkdl8hj3BeTl+KdJMoMHw8FlPli0NHavmoYm7oae2wP4RdfCWaBKVurDopZM
            iJbjCcNtbwnFEbyxW5bhYCGhYWLIG6ZMAg7rWH9GSFGxzRRYJaV3R/3W30qx4Zy8
            m2DLysm1uXOazVh8MptNZJmp4vqvZU1AQRUxnnHUdpsI8iDAhDtqwfEtErsp0AfP
            dWFTX152SlNvD5Xpd1iLODW88qNSt0Qe23Pswa8DDFRWg2z5uYibQbV69WWJ4wvU
            aAEJAhBred8ZQXaWk8TjZfqpoTrHOdvgZNo4ysEA4JOlmmLk7gHDFo3wMpLGZXal
            F5TLifg5wkVfNVCEIutJQif6/aDKRVlYquKjLxfvE6iXkkbvBDfUnFwy6UFaA0io
            DyJKHgpuDDvb
            =6TWO
            -----END PGP MESSAGE-----
          fp: 7A5DC69AD7F7A05AAF22EBD8005B9C45909B266E
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
