---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: syno-storage
provisioner: csi.san.synology.com
parameters:
  protocol: iscsi
  csi.storage.k8s.io/fstype: ext4
  dsm: 192.168.1.244
  location: "/volume1"
reclaimPolicy: Retain
allowVolumeExpansion: true
