apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9898
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  ingressClassName: public
  tls:
    - secretName: orriborri-com-tls
  rules:
    - host: ${PODINFO_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.9.4@sha256:b1e974022d6603c8ceea4a05c6ff9d9f4e6bf6a6590fb740251811283458c4ea
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
