apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-db-pvc
  namespace: sparkyfitness
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-backup-pvc
  namespace: sparkyfitness
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-uploads-pvc
  namespace: sparkyfitness
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
