apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  releaseName: homeassistant
  chart:
    spec:
      chart: home-assistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pajikos-home-assistant
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
  values:
    persistence:
      enabled: true
      storageClass: homelab-nfs
      accessMode: ReadWriteMany
      size: 10Gi
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        kubernetes.io/ingress.class: public
      hosts:
        - host: ha.orriborri.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - ha.orriborri.com
          secretName: orriborri-com-tls
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
