apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  releaseName: homeassistant
  chart:
    spec:
      chart: home-assistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: small-hack-home-assistant
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
  values:
    persistence:
      enabled: true
      storageClass: syno-storage
      accessMode: ReadWriteOnce
      size: 10Gi
    ingress:
      enabled: true
      ingressClassName: public
      hosts:
        - host: homeassistant.orriborri.com
          paths:
            - /
      tls:
        - secretName: orriborri-com-tls
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
