apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: default # Ensure it's the same namespace as your service
spec:
  ingressClassName: private
  tls:
    - secretName: orriborri-com-tls
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/enable-websockets: "true"
  rules:
    - host: ha.orriborri.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: home-assistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 400Mi
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: homelab-nfs
    service:
      type: LoadBalancer
      port: 80
      targetPort: 8123
    configuration:
      enabled: true
      templateConfig: |-
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.244.0.0/16
