apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-podcast-data-v2
  namespace: default
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-data-v2
  namespace: default
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 65Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-data-v2
  namespace: default
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi # Increased from 20Gi to 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-data-v2
  namespace: default
spec:
  storageClassName: homelab-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
