apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-podcast-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 130Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 65Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
