apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
