apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-books
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
