apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kavita
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: kavita
      version: "12.0.7"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/jvmilazz0/kavita
      tag: 0.8.7@sha256:b9c671586db2a6a688da3cb4b45f1319cca33b01e6e760c8bf3c19d60101bdf2
      pullPolicy: IfNotPresent
    
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    
    service:
      main:
        ports:
          main:
            targetPort: 5000
            port: 10189
    
    persistence:
      config:
        enabled: true
        mountPath: "/kavita/config"
        storageClass: syno-storage
        accessMode: ReadWriteMany
        size: 10Gi
      
      manga:
        enabled: true
        mountPath: "/manga"
        storageClass: syno-storage
        accessMode: ReadWriteMany
        size: 100Gi
      
      books:
        enabled: true
        mountPath: "/books"
        storageClass: syno-storage
        accessMode: ReadWriteMany
        size: 100Gi
    
    ingress:
      main:
        enabled: true
        ingressClassName: public
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        tls:
          - secretName: orriborri-com-tls
        hosts:
          - host: kavita.orriborri.com
            paths:
              - path: /
                pathType: Prefix
