apiVersion: apps/v1
kind: Deployment
metadata:
  name: penpot-backend
  namespace: default
  labels:
    app: penpot-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: penpot-backend
  template:
    metadata:
      labels:
        app: penpot-backend
    spec:
      containers:
        - name: penpot-backend
          image: penpotapp/backend:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6060
          envFrom:
            - secretRef:
                name: penpot-config
          env:
            # Keep database credentials from shared postgres-config
            - name: PENPOT_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: PENPOT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /opt/data/assets
              name: assets-data
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
      volumes:
        - name: assets-data
          persistentVolumeClaim:
            claimName: penpot-assets-data
