apiVersion: apps/v1
kind: Deployment
metadata:
  name: penpot-backend
  namespace: default
  labels:
    app: penpot-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: penpot-backend
  template:
    metadata:
      labels:
        app: penpot-backend
    spec:
      # Set proper security context for Penpot
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
      # Add init container to fix permissions
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /opt/data/assets && chmod -R 755 /opt/data/assets"]
          volumeMounts:
            - mountPath: /opt/data/assets
              name: assets-data
          securityContext:
            runAsUser: 0  # Run as root to change ownership
      containers:
        - name: penpot-backend
          image: penpotapp/backend:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6060
          envFrom:
            - secretRef:
                name: penpot-config
          env:
            # Keep database credentials from shared postgres-config
            - name: PENPOT_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: PENPOT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /opt/data/assets
              name: assets-data
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: assets-data
          persistentVolumeClaim:
            claimName: penpot-assets-data
