apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-assets-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
