apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: default
  labels:
    app: calibre-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: lscr.io/linuxserver/calibre-web:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-calibre"
          volumeMounts:
            - mountPath: /config
              name: calibre-web-config
            - mountPath: /books
              name: calibre-library
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: calibre-web-config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: calibre-library
          persistentVolumeClaim:
            claimName: calibre-library
